version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region eu-west-1 | docker login --username DevOps_user --password-stdin 288761743924.dkr.ecr.eu-west-1.amazonaws.com/hello-django)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hello-django .
      - docker tag hello-django:latest 288761743924.dkr.ecr.eu-west-1.amazonaws.com/hello-django:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 288761743924.dkr.ecr.eu-west-1.amazonaws.com/hello-django:latest
      - echo Build completed on `date`

artifacts:
  files: '**/*'
