version: 0.2
runtime-versions:
  python: 3.11
  
phases:
  install:
    runtime-versions:
      python: 3.11  # Change if you're using a different version
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - yum install -y sqlite sqlite-devel
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - export DJANGO_SETTINGS_MODULE=Hello_World.settings  # Update this!
      - python manage.py makemigrations
      - python manage.py migrate

  build:
    commands:
      - echo "Build phase - running tests (optional)"
      # - python manage.py test  # Remove if you don't want tests here

  post_build:
    commands:
      - echo "Post build - Build complete."

artifacts:
  files:
    - '**/*'
  discard-paths: no
