version: 0.2

phases:
  install:
    commands:
      # - echo "Installing system dependencies..."
      # - yum install -y gcc gcc-c++ make sqlite sqlite-devel bzip2 bzip2-devel zlib zlib-devel xz xz-devel libffi-devel
      # - echo "Installing Python dependencies..."
      # - pip install --upgrade pip
      # - pip install -r requirements.txt
      

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # - export DJANGO_SETTINGS_MODULE=Hello_World.settings  # ✅ Update if needed
      # - python manage.py makemigrations
      # - python manage.py migrate
      - docker build -t django_github .

  build:
    commands:
      - echo "Build phase - running tests (optional)"
      # - python manage.py test
      - docker images
      - docker run django_github 

  post_build:
    commands:
      - echo "Post build - Build complete."

artifacts:
  files:
    - '**/*'
  discard-paths: no
